"""玹翔旅遊 v8.0 網站發布清單。"""

SITE_URL = "https://xuanxiangtravel.com"
FIREBASE_DATABASE_ID = "xuanxiangtravel"

INDEXABLE = [
    "index.html",
    "about.html",
    "airport.html",
    "airport-pricing.html",
    "port.html",
    "port-pricing.html",
    "charter.html",
    "travel-charter.html",
    "tour-pricing.html",
    "mountain.html",
    "mountain-pricing.html",
    "long-distance.html",
    "long-distance-pricing.html",
    "business.html",
    "business-transfer.html",
    "concert.html",
    "concert-transfer.html",
    "pet-transfer.html",
    "wedding-car.html",
    "car-rental.html",
    "price.html",
    "product.html",
    "booking.html",
    "fleet.html",
    "vehicles.html",
    "faq.html",
    "terms.html",
    "charter-policy.html",
    "transfer-policy.html",
    "privacy.html",
    "ocba.html",
    "travel-one-day.html",
    "travel-two-days.html",
    "travel-three-days.html",
    "smangus-day.html",
    "hehuanshan-day.html",
    "qingjing-sunmoonlake-day.html",
    "travel-region.html",
    "school-airport.html",
    "school-tour.html",
    "school-mountain.html",
    "school-secret.html",
    "school-hiking.html",
    "driver-recruit.html",
    "store-cooperation.html",
    "addons.html",
]

NOINDEX = {
    "404.html",
    "README.html",
    "booking-success.html",
    "content-merged.html",
    "forgot-password.html",
    "login.html",
    "member-center.html",
    "member-login.html",
    "member.html",
    "register.html",
    "travel-hehuanshan.html",
    "travel-sunmoonlake.html",
}

BLOCKED_ROUTES = [
    "/apps-script/*",
    "/tools/*",
    "/docs/*",
    "/README.html",
    "/content-merged.html",
    "/*.txt",
    "/firebase.json",
    "/firestore.rules",
    "/firestore.indexes.json",
]
